apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-lake-grpc-generator
  namespace: new-lake
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: new-lake-grpc-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: new-lake-grpc-generator
    spec:
      containers:
      - name: new-lake-grpc-generator
        image: vertwave/new-lake-grpc-generator:1.0.0
        envFrom:
          - configMapRef:
              name: new-lake-grpc-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never
      # imagePullSecrets:
      # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: new-lake-grpc-generator-service
  namespace: new-lake
spec:
  selector:
    app: new-lake-grpc-generator
  clusterIP: None

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: new-lake-grpc-config
  namespace: new-lake
data:
  ServiceSettings__DelayInterval: '1000'
  ServiceSettings__MessageId: '1'
  ServiceSettings__ServerUrl: 'http://new-lake-grpc-api-service:5002'
  ServiceSettings__RetryCount: '5'
  ServiceSettings__RetryInterval: '5000'