
trigger:
- development

pr: none

resources:
- repo: self

variables:
  - name: tag
    value: $(Build.SourceBranchName).$(Build.BuildNumber).$(Build.BuildId)

stages:
- stage: Build

  displayName: Build image

  jobs:

  - job: Build
    displayName: Build

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      inputs:
        command: 'test'
        projects: '**/tests/*'

    - task: DockerCompose@0
      displayName: Multi Container Build
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: $(tag)

    - task: DockerCompose@0
      displayName: Multi Container Push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        additionalImageTags: $(tag)

    - task: replacetokens@5
      displayName: Replace YAML Tokens
      inputs:
        targetFiles: '**/src/k8s/_deploy/*.yml'
        encoding: 'auto'
        tokenPattern: 'azpipelines'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true

    - task: PublishBuildArtifacts@1
      displayName: Publish Manifests
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/src/k8s/_deploy'
        ArtifactName: 'drop'
        publishLocation: 'Container'