# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

pr: none

resources:
- repo: self

variables:
  - name: tag
    value: $(Build.SourceBranchName).$(Build.BuildNumber).$(Build.BuildId)

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: Multi Container Build
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: $(tag)

    - task: DockerCompose@0
      displayName: Multi Container Push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        additionalImageTags: $(tag)
