# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        includeSourceTags: true
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
        includeSourceTags: true
        includeLatestTag: true
