version: '3.8'

services:
  new-lake-api:
    image: new-lake-api:latest
    build: 
      context: .
      dockerfile: src/services/NewLake.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  new-lake-background-api:
    image: new-lake-background-api:latest
    build: 
      context: .
      dockerfile: src/services/NewLake.Background.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  new-lake-queue-listener:
    image: new-lake-queue-listener:latest
    build: 
      context: .
      dockerfile: src/services/NewLake.Queue.Listener/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production

  new-lake-grpc-server:
    image: new-lake-grpc-server:latest
    build: 
      context: .
      dockerfile: src/services/NewLake.GrpcServer/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production

  
  




    
