version: '3.8'

services:
  new-lake-api:
    image: vertwave/new-lake-api:1.0.0
    build: 
      context: .
      dockerfile: src/services/NewLake.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  new-lake-background-api:
    image: vertwave/new-lake-background-api:1.0.0
    build: 
      context: .
      dockerfile: src/services/NewLake.Background.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  new-lake-queue-listener:
    image: vertwave/new-lake-queue-listener:1.0.0
    build: 
      context: .
      dockerfile: src/services/NewLake.Queue.Listener/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production

  new-lake-grpc-generator:
    image: vertwave/new-lake-grpc-generator:1.0.0
    build: 
      context: .
      dockerfile: src/services/NewLake.GrpcGenerator/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production