apiVersion: v1
kind: ConfigMap
metadata:
  name: new-lake-config
data:
  RedisHost: $(RedisHost)
  QueueSettings__HostName: $(QueueSettings.HostName)
  QueueSettings__QueueName: $(QueueSettings.QueueName)
  QueueSettings__Exchange: $(QueueSettings.Exchange)
  QueueSettings__Topic: $(QueueSettings.Topic)
  QueueSettings__RoutingKey: $(QueueSettings.RoutingKey)

  TestSettings__Name: $(TestSettings.Name)
  TestSettings__Value: $(TestSettings.Value)