apiVersion: v1
kind: ConfigMap
metadata:
  name: new-lake-grpc-config
data:
  ServiceSettings__DelayInterval: $(GrpcService.DelayInterval)
  ServiceSettings__MessageId: $(GrpcService.MessageId)
  ServiceSettings__ServerUrl: $(GrpcService.ServerUrl)
  ServiceSettings__RetryCount: $(GrpcService.RetryCount)
  ServiceSettings__RetryInterval: $(GrpcService.RetryInterval)