apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-lake-grpc-generator  
spec:
  selector:
    matchLabels:
      app: new-lake-grpc-generator
  replicas: 1
  template:
    metadata:
      labels:
        app: new-lake-grpc-generator
    spec:
      containers:
      - name: new-lake-grpc-generator
        image: new-lake-grpc-generator:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: app/config
            name: config-volume
        imagePullPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: new-lake-grpc-config
---
apiVersion: v1
kind: Service
metadata:
  name: new-lake-grpc-generator-service
spec:
  selector:
    app: new-lake-grpc-generator
  clusterIP: None