apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-lake-api
  namespace: vwlocal
spec:
  selector:
    matchLabels:
      app: new-lake-api
  replicas: 1
  template:
    metadata:
      labels:
        app: new-lake-api
    spec:
      containers:
      - name: new-lake-api
        image: new-lake-api:latest
        env:
        - name: DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2UNENCRYPTEDSUPPORT
          value: "true"
        envFrom:
          - configMapRef:
              name: new-lake-config
        ports:
        - containerPort: 5001
        - containerPort: 5002
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: new-lake-api-service
  namespace: vwlocal
spec:
  selector:
    app: new-lake-api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-unsecured
      port: 5001
      targetPort: 5001


---
apiVersion: v1
kind: Service
metadata:
  name: new-lake-grpc-api-service
  namespace: vwlocal
spec:
  selector:
    app: new-lake-api
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http2-grpc
      port: 5002
      targetPort: 5002
