apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-lake-queue-listener
  namespace: vwlocal
spec:
  selector:
    matchLabels:
      app: new-lake-queue-listener
  replicas: 1
  template:
    metadata:
      labels:
        app: new-lake-queue-listener
    spec:
      containers:
      - name: new-lake-queue-listener
        image: new-lake-queue-listener:latest
        envFrom:
          - configMapRef: 
              name: new-lake-config        
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: new-lake-queue-listener-service
  namespace: vwlocal
spec:
  selector:
    app: new-lake-queue-listener
  clusterIP: None 