apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq-app
  namespace: new-lake
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: seq-app
  replicas: 1
  template:
    metadata:
      labels:
        app: seq-app
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
          ports:
          - containerPort: 5341
          - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "400m"

---
apiVersion: v1
kind: Service
metadata:
  name: seq-service
  namespace: new-lake
spec:
  selector:
    app: seq-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31534

---
apiVersion: v1
kind: Service
metadata:
  name: seq-ingest
  namespace: new-lake
spec:
  clusterIP: None
  selector:
    app: seq-app
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341